eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://truflux-service-registry:8762/eureka/
  instance:
    hostname: truflux-service-registry
